### ISSUE TITLE
oshi version upgrade ?

### ISSUE THREAD

**Issue by theute** [hawkular/hawkular-agent#216]
is there a particular reason to use that old version of oshi ?
    <version.com.github.dblock>1.5</version.com.github.dblock>

v2.6.2 is available but I didn't try it.

(v1.5 complains about my raspberry, nothing blocking for my demo, just the following error in the logs many times)

2016-06-22 14:32:12,488 ERROR [org.hawkular.agent.monitor.protocol.EndpointService](Hawkular WildFly Agent Full Discovery Scan-1) HAWKMONITOR010049: Could not access resources of endpoint [PlatformEndpointService[Endpoint[platform]:[null]]]: org.hawkular.agent.monitor.protocol.ProtocolException: java.lang.IllegalArgumentException: Processor number (4) must be less than the number of CPUs: 4
    at org.hawkular.agent.monitor.protocol.platform.PlatformDriver.fetchNodes(PlatformDriver.java:60)
    at org.hawkular.agent.monitor.protocol.platform.PlatformDriver.fetchNodes(PlatformDriver.java:38)
    at org.hawkular.agent.monitor.protocol.Discovery.discoverChildren(Discovery.java:72)
    at org.hawkular.agent.monitor.protocol.Discovery.discoverChildren(Discovery.java:105)
    at org.hawkular.agent.monitor.protocol.EndpointService.discoverChildren(EndpointService.java:251)
    at org.hawkular.agent.monitor.protocol.EndpointService$1.run(EndpointService.java:204)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.IllegalArgumentException: Processor number (4) must be less than the number of CPUs: 4
    at oshi.software.os.linux.proc.CentralProcessor.<init>(CentralProcessor.java:125)
    at oshi.software.os.linux.LinuxHardwareAbstractionLayer.getProcessors(LinuxHardwareAbstractionLayer.java:81)
    at org.hawkular.agent.monitor.protocol.platform.OshiPlatformCache.getProcessors(OshiPlatformCache.java:187)
    at org.hawkular.agent.monitor.protocol.platform.OshiPlatformCache.discoverResources(OshiPlatformCache.java:438)
    at org.hawkular.agent.monitor.protocol.platform.PlatformDriver.fetchNodes(PlatformDriver.java:53)
    ... 9 more

**Comment by jmazzitelli** [comment]
I know of no reason why we can't update Oshi.

**Comment by jmazzitelli** [comment]
Just did a quick test - immediately got compile errors when upgrading. So some work would need to be done.

**Comment by jmazzitelli** [comment]
Wow, they completely changed the API - specifically around the CPU stuff. This would require some work to upgrade.

**Comment by jmazzitelli** [comment]
move to JIRA : https://issues.jboss.org/browse/HWKAGENT-115
